local_contexts_integration.settings:
  type: config_object
  label: "Local Contexts Integration Settings"
  mapping:
    api_key:
      type: string
      label: "API Key"
    api_url:
      type: string
      label: "API Base URL"
    field_identifier:
      type: string
      label: "Default Field for Retrieving Project ID"